name: Deploy to Hosting via FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Upload files to FTP

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp.bayarqris.net
          username: peakmiles@peakmiles.id
          password: peakmiles123
          port: 21
          server-dir: /
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            README.md
